---
title: "The relationship of video's catagories and video count on Youtube"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
mydata = head(read.csv(file="vocabulary.csv"),180)  # read csv file 
library(ggplot2)
```

```{r chart1}
theme_set(theme_classic())
gg = ggplot(data=mydata, aes(x=Vertical1))+
  geom_bar(aes(fill=Vertical1,colour = "white"))+
  coord_flip()+
  labs(x="catagories", 
       title="Videos catagory counts")
plot(gg)
```
```{r chart2}
theme_set(theme_classic())
qplot(TrainVideoCount,Vertical1,data=mydata)
```
```{r chart3}
theme_set(theme_classic())
gg = ggplot(data=mydata, aes(x=as.numeric(Index),y=TrainVideoCount),color=Vertical1)+
  geom_point()+
  geom_smooth(color = "red",size = 2)+
  labs(x="index(1 to 180)", y="videocount",
       title="Videos catagory counts")
plot(gg)
```
```{r chart 4}
theme_set(theme_classic())
gg = ggplot(data=mydata, aes(x=as.numeric(Index),y=log(TrainVideoCount)))+
  geom_point(aes(col=Vertical1))+
  geom_smooth(color = "yellow",size = 1)+
  labs(x="index(1 to 180)",y="videocount in log" ,
       title="Videos catagory counts")
plot(gg)
```

```{r datas}
mydata[1:180,c(1,2,6), drop=FALSE]
print("source:https://research.google.com/youtube8m/")
```
